{% set pyproject = load_file_data('../../pyproject.toml','toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project', {}) %}
package:
  name: dl1_data_handler
  version: {{ project.get('dynamic') }}
source:
  path: ../..
build:
  noarch: generic
  #number: 0
  string: {{ 'py'+ PY_VER.replace('.','') + '_' + environ.get('GIT_DESCRIBE_HASH', 'latest') }}
  script: python -m pip install .
  
requirements:
  build:
    - python #==3.12
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git
  host:
    - python #==3.12
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git
  run:
    - python #==3.12
    - numpy >=1.20
    - jupyter
    - astropy
    - scipy
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git

  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - nietootein
    - TjarkMiener

