{% set data = load_setup_py_data() %}

package:
  name: dl1_data_handler
  version: {{ data.get('version') }}
source:
  path: ../..

build:
  #noarch: generic
  number: 0
  
requirements:
  build:
    - python #==3.12
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.21.1
    - pytables >=3.8
    - pandas
    - git
  host:
    - python #==3.12
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.21.1
    - pytables >=3.8
    - pandas
    - git
  run:
    - python #==3.12
    - numpy >=1.20
    - jupyter
    - astropy
    - scipy
    - ctapipe ==0.21.1
    - pytables >=3.8
    - pandas
    - git

  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - nietootein
    - TjarkMiener

