# conda env create -f environment-magic.yml
name: dl1dh_magic
channels:
    - anaconda
    - conda-forge
    - cta-observatory
dependencies:
    - python>=3.8
    - astropy<5,>=4.0.5
    - numpy
    - uproot
    - ctapipe==0.9.1
    - ctapipe-extra
    - pip
    - pyyaml
    - pandas
    - pip:
        - pydot

