package:
  name: dl1_data_handler
  version: "0.7.5"

source:
  git_rev: v0.7.5
  git_url: https://github.com/cta-observatory/dl1-data-handler.git

build:
  number: 0

requirements:
  build:
    - python >=3.6.0
    - setuptools 
  host:
    - python >=3.6.0
    - ctapipe >=0.6.2
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4
  run:
    - python >=3.6.0
    - ctapipe >=0.6.2
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4
  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - bryankim96
    - aribrill
    - nietootein
