package:
  name: dl1_data_handler
  version: "0.8.2"

source:
  git_url: https://github.com/cta-observatory/dl1-data-handler.git
  git_rev: v0.8.2

build:
  number: 0

requirements:
  build:
    - python >=3.7.6
    - numpy >=1.15.0
    - ctapipe ==0.8.0
    - pytables >=3.4.4 
  host:
    - python >=3.7.6
    - numpy >=1.15.0
    - ctapipe ==0.8.0
    - pytables >=3.4.4
  run:
    - python >=3.7.6
    - numpy >=1.15.0
    - ctapipe ==0.8.0
    - pytables >=3.4.4
  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - aribrill
    - nietootein
    - TjarkMiener
    - vuillaut
    - mikael10j
