package:
  name: dl1_data_handler
  version: "0.10.4"

source:
  #path: ./
  git_url: https://github.com/cta-observatory/dl1-data-handler.git
  git_rev: v0.10.4

build:
  noarch: generic
  number: 0

requirements:
  build:
    - python ==3.7
    - numpy >=1.15.0
    - jupyter
    - ctapipe ==0.12.0
    - pytables >=3.4.4 
    - pandas
  host:
    - python ==3.7
    - numpy >=1.15.0
    - jupyter
    - ctapipe ==0.12.0
    - pytables >=3.4.4
    - pandas
  run:
    - python ==3.7
    - numpy >=1.15.0
    - jupyter
    - ctapipe ==0.12.0
    - pytables >=3.4.4
    - pandas
  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - aribrill
    - nietootein
    - TjarkMiener
    - vuillaut
    - mikael10j
