package:
  name: dl1_data_handler
  version: "0.7.4"

source:
  git_rev: v0.7.4
  git_url: https://github.com/cta-observatory/dl1-data-handler.git

requirements:
  host:
    - python >=3.5.0
    - setuptools

  run:
    - python >=3.5.0
    - pyhessio >=2.1.1
    - ctapipe >=0.6.2
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4

  test:
    imports:
      -dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
