
package:
  name: dl1_data_handler
  version: {{ GIT_DESCRIBE_TAG }}
source:
  #path: ./
  git_url: https://github.com/cta-observatory/dl1-data-handler.git
  git_rev: {{ GIT_DESCRIBE_TAG }}

build:
  #noarch: generic
  number: 0
  
requirements:
  build:
    - python
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git
  host:
    - python
    - numpy >=1.20
    - astropy
    - scipy
    - jupyter
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git
  run:
    - python
    - numpy >=1.20
    - jupyter
    - astropy
    - scipy
    - ctapipe ==0.20.0
    - pytables >=3.8
    - pandas
    - git

  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - nietootein
    - TjarkMiener

