
name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Daily at 02:00 UTC

jobs:
  cache-test-data:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache test data
        id: cache-data
        uses: actions/cache@v4
        with:
          path: ~/.cache/ctapipe
          key: ctapipe-data-${{ runner.os }}-v1
      - name: Install ctapipe and download data
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: |
          pip install ctapipe
          python -c "from ctapipe.utils import get_dataset_path; get_dataset_path('gamma_prod5.simtel.zst')"

  build:
    needs: cache-test-data
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.12', '3.13', '3.14']
        ctapipe-version: ['0.25.0', 'latest', 'nightly']
      max-parallel: 6
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    # Allow failures for nightly ctapipe builds
    continue-on-error: ${{ matrix.ctapipe-version == 'nightly'}}
    steps:
      - uses: actions/checkout@v4

      - name: Restore test data cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ctapipe
          key: ctapipe-data-${{ runner.os }}-v1

      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.ctapipe-version }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: "latest"
          use-mamba: true
          activate-environment: dl1dh
          python-version: ${{ matrix.python-version }}

      - name: Pre-script setup
        run: |
          pip install --upgrade pip
          pip install pylint pylint-exit anybadge
          pip install eventio
          if [ "${{ matrix.ctapipe-version }}" = "nightly" ]; then
            pip install git+https://github.com/cta-observatory/ctapipe.git
          elif [ "${{ matrix.ctapipe-version }}" = "latest" ]; then
            pip install ctapipe
          else
            pip install ctapipe==${{ matrix.ctapipe-version }}
          fi
          pip install pytest flake8

      - name: Add MKL_THREADING_LAYER variable
        run: echo "MKL_THREADING_LAYER=GNU" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install package with pip
        run: |
          pip install -e .[tests]

      - name: Run pytest
        run: |
          pytest
